# base is Ubuntu 16.04
FROM ubuntu:16.04
MAINTAINER Dummy <dummy@dummy.com>

# Start docker file
RUN echo "now building..."

# update apt-get
RUN apt-get update --fix-missing

# setup workdir
WORKDIR /home/development/

# add install directory
ADD docker/install install/

# install core packages
RUN set -x && \
    bash install/ubuntu_install_core_packages.sh

# install Python and Pip
RUN set -x && \
    bash install/ubuntu_install_python.sh

# build openCV
RUN set -x && \
    bash install/ubuntu_install_opencv.sh

# install gstreamer
RUN set -x && \
    bash install/ubuntu_install_gstreamer.sh

# install Tensorflow and openCV
RUN pip3 install numpy tensorflow opencv-python

# install SageMaker Neo Runtime
RUN set -x && \
    bash install/ubuntu_install_sagemaker_neo.sh

# install python packages
RUN set -x && \
    pip3 install psutil && pip install psutil && \
    pip3 install pillow && pip install pillow

# install tensorflow models
RUN set -x && \
    git clone --recursive https://github.com/tensorflow/models && \
    pip3 install models/research && pip install models/research

# start bash
CMD [ '/bin/bash'  ]
