# base is Ubuntu 16.04
FROM ubuntu:16.04
MAINTAINER Dummy <dummy@dummy.com>

# Start docker file
RUN echo "now building..."

# update apt-get
RUN apt-get update --fix-missing

# install core packages
RUN set -x && \
    apt-get install -y git && \
    apt-get install -y wget && \
    apt-get install -y vim

# setup workdir
WORKDIR /home/development/

# install Python and Pip
ADD docker/install install/
RUN set -x && \
    bash install/ubuntu_install_python.sh

# install cmake
RUN set -x && \
    mkdir tmp_cmake && cd tmp_cmake && \
    wget https://github.com/Kitware/CMake/releases/download/v3.6.2/cmake-3.6.2.tar.gz && \
    tar xvf cmake-3.6.2.tar.gz && cd cmake-3.6.2 && \
    ./bootstrap && make && make install

# install c compiler
RUN apt-get install -yq make gcc g++ unzip build-essential gcc zlib1g-dev

# build openCV
RUN ln -s /usr/include/libv4l1-videodev.h /usr/include/linux/videodev.h
RUN mkdir tmp
RUN cd tmp && wget https://github.com/Itseez/opencv/archive/3.1.0.zip && unzip 3.1.0.zip
RUN cd tmp/opencv-3.1.0 && cmake CMakeLists.txt -DWITH_TBB=ON \
                                                  -DINSTALL_CREATE_DISTRIB=ON \
                                                  -DWITH_FFMPEG=OFF \
                                                  -DWITH_IPP=OFF \
                                                  -DCMAKE_INSTALL_PREFIX=/usr/local
RUN cd tmp/opencv-3.1.0 && make -j2 && make install

# install Tensorflow and openCV
RUN pip3 install numpy tensorflow opencv-python

# install SageMaker Neo Runtime
RUN set -x && \
    git clone --recursive https://github.com/neo-ai/neo-ai-dlr
RUN set -x && \
    cd neo-ai-dlr && \
    mkdir build && cd build && \
    cmake .. && \
    make -j4 && \
    cd ../python && python3 setup.py install --user

# install python packages
RUN set -x && \
    pip3 install psutil && pip install psutil && \
    pip3 install pillow && pip install pillow

# install tensorflow models
RUN set -x && \
    git clone --recursive https://github.com/tensorflow/models && \
    pip3 install models/research && pip install models/research

# test sagemaker neo runtime
RUN set -x && \
    python3 -c "import dlr"

# remove temporary directory
RUN set -x && \
    rm -rf tmp tmp_cmake

# start bash
CMD [ '/bin/bash'  ]
